### ISSUE TITLE
Wondering if this is being used in production ...

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando-stups/stups-build#1]
Hi -- it doesn't have a README posted; is documentation elsewhere for Zalandos/others to find?

**Comment by jbellmann** [comment]
Hi Lauri,
yes it is. It's common Maven-configuration used by some libraries in 'zalando-stups'. Mostly used as 'parent' to avoid writing same xml in poms again and again.

**Comment by lasomethingsomething** [comment]
Got it, thanks. I've included your point here in README.md, just so other Zalandos (especially new members of the tech team) are aware.
